version: '3.8'

services:
  lot-render:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./input
        target: /app/input
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
