services:
  lot-render:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/app/src
      - ./input:/app/input  # For CSV files
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
