services:

  # crawlers:
  #   build:
  #     context: .  # The root directory is used as the build context
  #     dockerfile: ./crawlers/Dockerfile  # Path to the Dockerfile inside the crawlers folder
  #   command: uvicorn main:app --host 0.0.0.0 --port 81
  #   volumes:
  #     - ./messaging:/app/messaging
  #     - ./shared:/app/shared
  #     - ./crawlers:/app/crawlers
  #     - ./etapa1-gethome-90ec2c4cffef.json:/app/etapa1-gethome-90ec2c4cffef.json  # Mount the service account JSON file
  #   ports:
  #     - "8001:81"
  #   working_dir: /app/crawlers/src
  #   env_file:
  #     - .env
  #   environment:
  #     - PYTHONPATH=/app
  #     - GOOGLE_APPLICATION_CREDENTIALS=/app/etapa1-gethome-90ec2c4cffef.json  # Set the environment variable

  properties:
    build:
      context: .  # The root directory is used as the build context
      dockerfile: ./properties/Dockerfile  # Path to the Dockerfile inside the properties folder
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./messaging:/app/messaging
      - ./shared:/app/shared
      - ./properties:/app/properties
      - ./etapa1-gethome-90ec2c4cffef.json:/app/etapa1-gethome-90ec2c4cffef.json  # Mount the service account JSON file
    ports:
      - "8000:80"
    working_dir: /app/properties/src
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - GOOGLE_APPLICATION_CREDENTIALS=/app/etapa1-gethome-90ec2c4cffef.json  # Set the environment variable

  auth:
    build:
      context: .  # The root directory is used as the build context
      dockerfile: ./auth/Dockerfile  # Path to the Dockerfile inside the auth folder
    command: uvicorn main:app --host 0.0.0.0 --port 82 --reload
    volumes:
      - ./messaging:/app/messaging
      - ./shared:/app/shared
      - ./auth:/app/auth
      - ./etapa1-gethome-90ec2c4cffef.json:/app/etapa1-gethome-90ec2c4cffef.json  # Mount the service account JSON file
    ports:
      - "8002:82"
    working_dir: /app/auth/src
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - GOOGLE_APPLICATION_CREDENTIALS=/app/etapa1-gethome-90ec2c4cffef.json  # Set the environment variable
      - ENVIRONMENT=development

  account:
    build:
      context: .  # The root directory is used as the build context
      dockerfile: ./account/Dockerfile  # Path to the Dockerfile inside the properties folder
    command: uvicorn main:app --host 0.0.0.0 --port 83 --reload
    volumes:
      - ./messaging:/app/messaging
      - ./shared:/app/shared
      - ./account:/app/account
      - ./etapa1-gethome-90ec2c4cffef.json:/app/etapa1-gethome-90ec2c4cffef.json  # Mount the service account JSON file
    ports:
      - "8003:83"
    working_dir: /app/account/src
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - GOOGLE_APPLICATION_CREDENTIALS=/app/etapa1-gethome-90ec2c4cffef.json  # Set the environment variable

  real_estate:
    build:
      context: .  # The root directory is used as the build context
      dockerfile: ./real_estate/Dockerfile  # Path to the Dockerfile inside the properties folder
    command: uvicorn main:app --reload --host 0.0.0.0 --port 84
    volumes:
      - ./messaging:/app/messaging
      - ./shared:/app/shared
      - ./real_estate:/app/real_estate
      - ./etapa1-gethome-90ec2c4cffef.json:/app/etapa1-gethome-90ec2c4cffef.json  # Mount the service account JSON file
    ports:
      - "8004:84"
    working_dir: /app/real_estate/src
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - GOOGLE_APPLICATION_CREDENTIALS=/app/etapa1-gethome-90ec2c4cffef.json  # Set the environment variable

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  #   env_file:
  #     - .env

  # consumer:
  #   build:
  #     context: .  # The root directory is used as the build context
  #     dockerfile: ./messaging/Dockerfile  # Path to the Dockerfile inside the messaging folder
  #   volumes:
  #     - ./messaging:/app/messaging
  #   env_file:
  #     - .env
  #   environment:
  #     - PYTHONPATH=/app
  #   depends_on:
  #     - rabbitmq  # Ensure RabbitMQ is started before the consumer
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"


  bigfive:
    build:
      context: .  # The root directory is used as the build context
      dockerfile: ./bigfive/Dockerfile  # Path to the Dockerfile inside the bigfive folder
    command: uvicorn main:app --host 0.0.0.0 --port 85 --reload
    volumes:
      - ./shared:/app/shared
      - ./bigfive:/app/bigfive
      - ./etapa1-gethome-90ec2c4cffef.json:/app/etapa1-gethome-90ec2c4cffef.json  # Mount the service account JSON file
    ports:
      - "8005:85"
    working_dir: /app/bigfive/src
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - GOOGLE_APPLICATION_CREDENTIALS=/app/etapa1-gethome-90ec2c4cffef.json  # Set the environment variable
      - ENVIRONMENT=development